version: '3.7'
services:

  composer:
    image: composer:2.5.5
    command: install --no-dev
    user: 1000:1000
    volumes:
      - "./:/app"

  app:
    image: php:8.2-fpm-alpine
    command: php-fpm
    working_dir: /app
    environment:
      - PHP_EXTENSIONS=fileinfo
    user: 1000:1000
    depends_on:
      composer:
        condition: service_completed_successfully
    volumes:
      - "./:/app"
      - "./input:/app/input:rw"
      - "./output:/app/output:rw"
